# -*- coding: utf-8 -*-
{
    'name': 'Employee Attendance Integration and  Shift Management',
    "author": "Hashcode IT Solutions",
    'website': 'https://hashcodeit.com/',
    'version': '14.0.1.0.6',
    'support': 'info@hashcodeit.com',
    'category': 'Human Resources',
    'summary': 'Apps for Calculate Mandatory Hours and Extra Hours of the Employee from Employee Check in and Check out Process.',
    'description': """ """,
    'depends': ['hr', 'hr_attendance', 'resource', 'hr_work_entry', 'mail', 'hr_payroll', 'hc_branch', 'hr_holidays',
                'hc_payroll_customization', 'hr_employee_firstname'],
    'data': [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/cron_job.xml",
        "data/sequence.xml",
        "views/res_company.xml",
        "views/attendance_views.xml",
        "views/hr_work_entry_type.xml",
        "views/attendance_raw_data.xml",
        "views/attendance_exception_data.xml",
        "views/resource_calendar_leave_views.xml",
        "views/over_time_type_views.xml",
        "views/hr_contract_views.xml",
        "views/time_off_type_views.xml",
    ],
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python" : ["simplejson"]},
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
}
