# -*- coding: utf-8 -*-
{
    'name': 'Air Ticket Request',
    "author": 'asn',
    'maintainer': 'asn',
    'company': 'Hash Code IT Solutions',
    'website': 'https://hashcodeit.com/',
    'version': '14.0.1.0.0',
    'support': 'info@hashcodeit.com',
    'category': 'Human Resources',
    'summary': 'Appraisal Extended',
    'description': """ Air Ticket Request """,
    'depends': ['web', 'hr_appraisal', 'hr_contract', 'hc_payroll_customization'],
    'data': [
        'security/ir.model.access.csv',
        'views/ticket_request_view.xml',
        'views/hr_payslip_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_leave_view.xml',
    ],
    "images": ["static/description/icon.png"],
    'license': 'OPL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
